### ISSUE TITLE
gem cant find it

### ISSUE THREAD

**Issue by RobTranquillo** [ricn/rika#10]
I'am a complete ruby & gem noob, but i think it doesn't work anymore with gem:
$ gem install rika
ERROR:  Could not find a valid gem 'rika' (>= 0) in any repository
ERROR:  Possible alternatives: RIMA, ika, pika, rik, riki

**Comment by ricn** [comment]
Make sure you are using JRuby. Ruby MRI will not work.

**Comment by RobTranquillo** [comment]
I was pretty shure i'am using jruby, but rvm info says different now. So its my fault, sorry.

**Comment by ricn** [comment]
No problem 😀
